# Generated by Django 4.2.2 on 2023-06-08 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('other1', models.TextField(null=True)),
                ('other2', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year', models.DateField()),
                ('event_data1', models.DateField()),
                ('event_data2', models.DateField(null=True)),
                ('event_data3', models.DateField(null=True)),
                ('event_data4', models.DateField(null=True)),
                ('event_data5', models.DateField(null=True)),
                ('event_data6', models.DateField(null=True)),
                ('place', models.TextField(null=True)),
                ('official_url', models.TextField(null=True)),
                ('twitter_id', models.TextField(null=True)),
                ('insta_id', models.TextField(null=True)),
                ('image_url1', models.TextField(null=True)),
                ('image_url2', models.TextField(null=True)),
                ('image_url3', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=datetime.datetime.now)),
                ('username', models.TextField()),
                ('user_id', models.TextField()),
                ('email', models.TextField(null=True)),
                ('user_sns_id1', models.TextField(null=True)),
                ('user_sns_id2', models.TextField(null=True)),
                ('user_sns_id3', models.TextField(null=True)),
                ('password', models.TextField()),
                ('gender', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('residence', models.TextField(null=True)),
                ('active_level', models.IntegerField(null=True)),
                ('subscribe_level', models.IntegerField(null=True)),
                ('invitation_flg', models.BooleanField(null=True)),
                ('my_tite_list', models.TextField(null=True)),
                ('follow_list', models.TextField(null=True)),
                ('follower_list', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.IntegerField()),
                ('name', models.TextField()),
                ('place', models.TextField()),
                ('color', models.TextField(default='#C0C0C0')),
                ('fes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('allotted_time', models.IntegerField()),
                ('artist_name', models.TextField()),
                ('apparence_flg', models.BooleanField(null=True)),
                ('change_time_flg', models.BooleanField(null=True)),
                ('other1', models.TextField(null=True)),
                ('other2', models.TextField(null=True)),
                ('official_url', models.TextField(null=True)),
                ('twitter_id', models.TextField(null=True)),
                ('insta_id', models.TextField(null=True)),
                ('fes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fesmodel')),
                ('live_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorymodel')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stagemodel')),
            ],
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='fes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fesmodel'),
        ),
    ]
