# Generated by Django 4.2.2 on 2023-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stagemodel_stage_image_path1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='apparence_flg',
            field=models.BooleanField(default=True),
        ),
    ]
