# Generated by Django 4.2.2 on 2023-07-29 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sectionmodel_apparence_flg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('section_list', models.TextField(null=True)),
                ('my_section_list', models.TextField(null=True)),
                ('slot_num', models.IntegerField()),
                ('title', models.TextField(null=True)),
                ('explain', models.TextField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
            ],
        ),
    ]
