# Generated by Django 4.2.2 on 2023-07-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mysectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysectionmodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usermodel'),
            preserve_default=False,
        ),
    ]
