# Generated by Django 4.2.2 on 2023-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mysectionmodel_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fesmodel',
            old_name='event_data1',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='fesmodel',
            name='event_data2',
        ),
        migrations.RemoveField(
            model_name='fesmodel',
            name='event_data3',
        ),
        migrations.RemoveField(
            model_name='fesmodel',
            name='event_data4',
        ),
        migrations.RemoveField(
            model_name='fesmodel',
            name='event_data5',
        ),
        migrations.RemoveField(
            model_name='fesmodel',
            name='event_data6',
        ),
        migrations.RemoveField(
            model_name='mysectionmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='fesmodel',
            name='other1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fesmodel',
            name='other2',
            field=models.TextField(null=True),
        ),
    ]
