# Generated by Django 4.2.2 on 2023-07-30 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_event_data1_fesmodel_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytitemodel',
            name='fes_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.fesmodel'),
            preserve_default=False,
        ),
    ]
