# Generated by Django 4.2.2 on 2023-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mytitemodel_fes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysectionmodel',
            name='other3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mysectionmodel',
            name='other4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mysectionmodel',
            name='other5',
            field=models.TextField(null=True),
        ),
    ]
