# Generated by Django 4.2.2 on 2023-08-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mysectionmodel_other3_mysectionmodel_other4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysectionmodel',
            name='other3',
        ),
        migrations.RemoveField(
            model_name='mysectionmodel',
            name='other4',
        ),
        migrations.RemoveField(
            model_name='mysectionmodel',
            name='other5',
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='other3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='other4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='other5',
            field=models.TextField(null=True),
        ),
    ]
